### ISSUE TITLE
Cannot use Discord installed from Fedora packages, if a new version becomes available directly from Discord

### ISSUE THREAD

**Issue by giacecco** [discordlinux/support#20]
## Discord Username
giacecco

## Expected Behavior
I use Discord from the packages distributed by Fedora repos (rpmfusion-nonfree-updates). If a new version is available from Discord directly, when I launch Discord I am notified of a new version being available. I should be able to ignore the notification and keep using Discord normally, until the updated packages are available from rpmfusion-nonfree-updates.

## Actual Behavior
Launching Discord I am notified of a new version being available. I ignore the notification and Discord quits, so there is no way to use Discord unless I give up the rpmfusion-nonfree-updates packages.

## Steps to Reproduce the Problem

  1. Install Discord from Fedora packages (e.g. version 0.0.4)
  2. Wait for a new Discord version to become available from Discord directly (e.g. version 0.0.5)
  3. Launch Discord

## Specifications

  - Version: 0.0.4-1.fc27
  - Platform: Fedora 27
  - Subsystem: -
  
Suggested solution: create a command line argument that ignores checking for upgrades, or take control of the maintenance of the Fedora package, and hard code into those binaries that upgrades should not be checked.

**Comment by simoniz0r** [comment]
Please take this up with the rpmfusion maintainers, thanks.

**Comment by seancallaway** [comment]
RPMFusion package maintainer here. As the package maintainer, I have no ability to make the user's expected behavior work. 

Unless Discord would be willing to make the release tarballs available to us ahead of time so that we can get it packaged and released in tandem or Discord decides to make its own RPM releases, this is a going to be an ongoing problem. A command-line flag (or just the ability for the n-1 version to continue to operate) seems like it'd do the trick.

**Comment by simoniz0r** [comment]
@seancallaway Please [contact Discord staff](https://dis.gd/contact) with your problem.

@giacecco If you'd like a Discord package that will be kept up to date, feel free to use one of my [AppImage builds of Discord](http://www.simonizor.net/discord).
